### ISSUE TITLE
Datos por edad, sexo, etc

### ISSUE THREAD

**Issue by fesja** [codeforspain/ds-empleo#1]
Hola @calonso,

¿Se pueden sacar datos por edad, sexo? ¿Cual sería el formato más desagregado posible que no contenga ninguna suma para que cada uno saque los datos que quiera?

gracias

**Comment by calonso** [comment]
Hola!

Pues creo que lo más desagregado sería grupo de edad, sexo y relación con el empleo (parado, activo, etc...). Actualizo los datasets para que contengan el grano más fino.

**Comment by fesja** [comment]
Aparte de tener las stats generales en un archivo, que siempre vienen bien; si tenemos un archivo con todo desagregado muchísimo mejor! Genial :)
