### ISSUE TITLE
datapackage.json

### ISSUE THREAD

**Issue by calonso** [codeforspain/ds-empleo#2]
Dado que este repo consta de varios archivos de datos (nacional, por provincias, por comunidades...). Cómo debe reflejarse eso en el `datapackage.json`?

* Un `datapackage.json` por archivo?
* Un array de archivos dentro del `datapackage.json`?
* Otras ideas?

**Comment by inigoflores** [comment]
La [especificación](http://dataprotocols.org/data-packages/#resource-information) dice lo siguiente:

> Packaged data resources are described in the resources property of the package descriptor. This property is an array of values. Each value describes a single resource and MUST be a JSON object.

Según lo cual `"resources"` es un array de objetos. 

Échale un vistazo a como lo he hecho en ds-organizacion-administrativa/datapackage.json.

Parece que [valida bien](http://data.okfn.org/tools/view?url=https%3A%2F%2Fraw.githubusercontent.com%2Fcodeforspain%2Fds-organizacion-administrativa%2Fmaster%2Fdatapackage.json).

**Comment by calonso** [comment]
Ok, gracias @inigoflores !!
